name: cyber-software-dependency-mapping
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - pyarrow
  - python-dotenv
  - jupyterlab
  - ipykernel
  - ipywidgets
  - matplotlib
  - seaborn
  - tqdm
  - pip
  - pip:
      - neo4j
      - neo4j-viz
      - playwright
